name: Python calculator application

# The events, which will trigger the following actions
on:
  push:   # Push event on branch 'main'
    branches: [ "main" ]
  pull_request:   # Pull request on branch 'main'
    branches: [ "main" ]

# Read permission added
permissions:
  contents: read

# The job section defines the instructions that will be executed for the above events
jobs:

  build:  # 1. Build job 
    runs-on: ubuntu-latest   # The image for Virtual Machine (in GitHub server/runner) is Ubuntu

    # The steps for Build job
    steps:
    - uses: actions/checkout@v4   # Clones the content of my repository to the VM, where it will be executed 

    - name: Set up Python 3.10    # Sets up Python on the VM
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"   # Python version 3.10

    - name: Install dependencies   # Install dependencies on the VM
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest   # Execution of test cases using pytest
      run: |
        pytest
